%General Mission Analysis Tool(GMAT) Script
%Created: 2023-07-17 16:28:09


%----------------------------------------
%---------- Spacecraft
%----------------------------------------

Create Spacecraft DefaultSC;
GMAT DefaultSC.DateFormat = TAIModJulian;
GMAT DefaultSC.Epoch = '21545';
GMAT DefaultSC.CoordinateSystem = EarthMJ2000Eq;
GMAT DefaultSC.DisplayStateType = Keplerian;
GMAT DefaultSC.SMA = 6738;
GMAT DefaultSC.ECC = 1.000165799178311e-12;
GMAT DefaultSC.INC = 98;
GMAT DefaultSC.RAAN = 78;
GMAT DefaultSC.AOP = 0;
GMAT DefaultSC.TA = 0;
GMAT DefaultSC.DryMass = 850;
GMAT DefaultSC.Cd = 2.2;
GMAT DefaultSC.Cr = 1.8;
GMAT DefaultSC.DragArea = 15;
GMAT DefaultSC.SRPArea = 1;
GMAT DefaultSC.SPADDragScaleFactor = 1;
GMAT DefaultSC.SPADSRPScaleFactor = 1;
GMAT DefaultSC.AtmosDensityScaleFactor = 1;
GMAT DefaultSC.ExtendedMassPropertiesModel = 'None';
GMAT DefaultSC.NAIFId = -10000001;
GMAT DefaultSC.NAIFIdReferenceFrame = -9000001;
GMAT DefaultSC.OrbitColor = Red;
GMAT DefaultSC.TargetColor = Teal;
GMAT DefaultSC.OrbitErrorCovariance = [ 1e+70 0 0 0 0 0 ; 0 1e+70 0 0 0 0 ; 0 0 1e+70 0 0 0 ; 0 0 0 1e+70 0 0 ; 0 0 0 0 1e+70 0 ; 0 0 0 0 0 1e+70 ];
GMAT DefaultSC.CdSigma = 1e+70;
GMAT DefaultSC.CrSigma = 1e+70;
GMAT DefaultSC.Id = 'SatId';
GMAT DefaultSC.Attitude = CoordinateSystemFixed;
GMAT DefaultSC.SPADSRPInterpolationMethod = Bilinear;
GMAT DefaultSC.SPADSRPScaleFactorSigma = 1e+70;
GMAT DefaultSC.SPADDragInterpolationMethod = Bilinear;
GMAT DefaultSC.SPADDragScaleFactorSigma = 1e+70;
GMAT DefaultSC.AtmosDensityScaleFactorSigma = 1e+70;
GMAT DefaultSC.ModelFile = 'aura.3ds';
GMAT DefaultSC.ModelOffsetX = 0;
GMAT DefaultSC.ModelOffsetY = 0;
GMAT DefaultSC.ModelOffsetZ = 0;
GMAT DefaultSC.ModelRotationX = 0;
GMAT DefaultSC.ModelRotationY = 0;
GMAT DefaultSC.ModelRotationZ = 0;
GMAT DefaultSC.ModelScale = 1;
GMAT DefaultSC.AttitudeDisplayStateType = 'Quaternion';
GMAT DefaultSC.AttitudeRateDisplayStateType = 'AngularVelocity';
GMAT DefaultSC.AttitudeCoordinateSystem = EarthMJ2000Eq;
GMAT DefaultSC.EulerAngleSequence = '321';

%----------------------------------------
%---------- Spacecraft
%----------------------------------------

Create Spacecraft DefaultSC2;
GMAT DefaultSC2.DateFormat = TAIModJulian;
GMAT DefaultSC2.Epoch = '21545';
GMAT DefaultSC2.CoordinateSystem = EarthMJ2000Eq;
GMAT DefaultSC2.DisplayStateType = Keplerian;
GMAT DefaultSC2.SMA = 6738;
GMAT DefaultSC2.ECC = 9.999268032158899e-13;
GMAT DefaultSC2.INC = 98;
GMAT DefaultSC2.RAAN = 78;
GMAT DefaultSC2.AOP = 0;
GMAT DefaultSC2.TA = 90;
GMAT DefaultSC2.DryMass = 850;
GMAT DefaultSC2.Cd = 2.2;
GMAT DefaultSC2.Cr = 1.8;
GMAT DefaultSC2.DragArea = 15;
GMAT DefaultSC2.SRPArea = 1;
GMAT DefaultSC2.SPADDragScaleFactor = 1;
GMAT DefaultSC2.SPADSRPScaleFactor = 1;
GMAT DefaultSC2.AtmosDensityScaleFactor = 1;
GMAT DefaultSC2.ExtendedMassPropertiesModel = 'None';
GMAT DefaultSC2.NAIFId = -10000001;
GMAT DefaultSC2.NAIFIdReferenceFrame = -9000001;
GMAT DefaultSC2.OrbitColor = Red;
GMAT DefaultSC2.TargetColor = Teal;
GMAT DefaultSC2.OrbitErrorCovariance = [ 1e+70 0 0 0 0 0 ; 0 1e+70 0 0 0 0 ; 0 0 1e+70 0 0 0 ; 0 0 0 1e+70 0 0 ; 0 0 0 0 1e+70 0 ; 0 0 0 0 0 1e+70 ];
GMAT DefaultSC2.CdSigma = 1e+70;
GMAT DefaultSC2.CrSigma = 1e+70;
GMAT DefaultSC2.Id = 'SatId';
GMAT DefaultSC2.Attitude = CoordinateSystemFixed;
GMAT DefaultSC2.SPADSRPInterpolationMethod = Bilinear;
GMAT DefaultSC2.SPADSRPScaleFactorSigma = 1e+70;
GMAT DefaultSC2.SPADDragInterpolationMethod = Bilinear;
GMAT DefaultSC2.SPADDragScaleFactorSigma = 1e+70;
GMAT DefaultSC2.AtmosDensityScaleFactorSigma = 1e+70;
GMAT DefaultSC2.ModelFile = 'aura.3ds';
GMAT DefaultSC2.ModelOffsetX = 0;
GMAT DefaultSC2.ModelOffsetY = 0;
GMAT DefaultSC2.ModelOffsetZ = 0;
GMAT DefaultSC2.ModelRotationX = 0;
GMAT DefaultSC2.ModelRotationY = 0;
GMAT DefaultSC2.ModelRotationZ = 0;
GMAT DefaultSC2.ModelScale = 1;
GMAT DefaultSC2.AttitudeDisplayStateType = 'Quaternion';
GMAT DefaultSC2.AttitudeRateDisplayStateType = 'AngularVelocity';
GMAT DefaultSC2.AttitudeCoordinateSystem = EarthMJ2000Eq;
GMAT DefaultSC2.EulerAngleSequence = '321';

%----------------------------------------
%---------- Spacecraft
%----------------------------------------

Create Spacecraft DefaultSC3;
GMAT DefaultSC3.DateFormat = TAIModJulian;
GMAT DefaultSC3.Epoch = '21545';
GMAT DefaultSC3.CoordinateSystem = EarthMJ2000Eq;
GMAT DefaultSC3.DisplayStateType = Keplerian;
GMAT DefaultSC3.SMA = 6738.000000000003;
GMAT DefaultSC3.ECC = 9.998054656308297e-13;
GMAT DefaultSC3.INC = 98;
GMAT DefaultSC3.RAAN = 78;
GMAT DefaultSC3.AOP = 0;
GMAT DefaultSC3.TA = 180;
GMAT DefaultSC3.DryMass = 850;
GMAT DefaultSC3.Cd = 2.2;
GMAT DefaultSC3.Cr = 1.8;
GMAT DefaultSC3.DragArea = 15;
GMAT DefaultSC3.SRPArea = 1;
GMAT DefaultSC3.SPADDragScaleFactor = 1;
GMAT DefaultSC3.SPADSRPScaleFactor = 1;
GMAT DefaultSC3.AtmosDensityScaleFactor = 1;
GMAT DefaultSC3.ExtendedMassPropertiesModel = 'None';
GMAT DefaultSC3.NAIFId = -10000001;
GMAT DefaultSC3.NAIFIdReferenceFrame = -9000001;
GMAT DefaultSC3.OrbitColor = Red;
GMAT DefaultSC3.TargetColor = Teal;
GMAT DefaultSC3.OrbitErrorCovariance = [ 1e+70 0 0 0 0 0 ; 0 1e+70 0 0 0 0 ; 0 0 1e+70 0 0 0 ; 0 0 0 1e+70 0 0 ; 0 0 0 0 1e+70 0 ; 0 0 0 0 0 1e+70 ];
GMAT DefaultSC3.CdSigma = 1e+70;
GMAT DefaultSC3.CrSigma = 1e+70;
GMAT DefaultSC3.Id = 'SatId';
GMAT DefaultSC3.Attitude = CoordinateSystemFixed;
GMAT DefaultSC3.SPADSRPInterpolationMethod = Bilinear;
GMAT DefaultSC3.SPADSRPScaleFactorSigma = 1e+70;
GMAT DefaultSC3.SPADDragInterpolationMethod = Bilinear;
GMAT DefaultSC3.SPADDragScaleFactorSigma = 1e+70;
GMAT DefaultSC3.AtmosDensityScaleFactorSigma = 1e+70;
GMAT DefaultSC3.ModelFile = 'aura.3ds';
GMAT DefaultSC3.ModelOffsetX = 0;
GMAT DefaultSC3.ModelOffsetY = 0;
GMAT DefaultSC3.ModelOffsetZ = 0;
GMAT DefaultSC3.ModelRotationX = 0;
GMAT DefaultSC3.ModelRotationY = 0;
GMAT DefaultSC3.ModelRotationZ = 0;
GMAT DefaultSC3.ModelScale = 1;
GMAT DefaultSC3.AttitudeDisplayStateType = 'Quaternion';
GMAT DefaultSC3.AttitudeRateDisplayStateType = 'AngularVelocity';
GMAT DefaultSC3.AttitudeCoordinateSystem = EarthMJ2000Eq;
GMAT DefaultSC3.EulerAngleSequence = '321';

%----------------------------------------
%---------- Spacecraft
%----------------------------------------

Create Spacecraft DefaultSC4;
GMAT DefaultSC4.DateFormat = TAIModJulian;
GMAT DefaultSC4.Epoch = '21545';
GMAT DefaultSC4.CoordinateSystem = EarthMJ2000Eq;
GMAT DefaultSC4.DisplayStateType = Keplerian;
GMAT DefaultSC4.SMA = 6738;
GMAT DefaultSC4.ECC = 1.000161232660411e-12;
GMAT DefaultSC4.INC = 98;
GMAT DefaultSC4.RAAN = 78;
GMAT DefaultSC4.AOP = 0;
GMAT DefaultSC4.TA = 270;
GMAT DefaultSC4.DryMass = 850;
GMAT DefaultSC4.Cd = 2.2;
GMAT DefaultSC4.Cr = 1.8;
GMAT DefaultSC4.DragArea = 15;
GMAT DefaultSC4.SRPArea = 1;
GMAT DefaultSC4.SPADDragScaleFactor = 1;
GMAT DefaultSC4.SPADSRPScaleFactor = 1;
GMAT DefaultSC4.AtmosDensityScaleFactor = 1;
GMAT DefaultSC4.ExtendedMassPropertiesModel = 'None';
GMAT DefaultSC4.NAIFId = -10000001;
GMAT DefaultSC4.NAIFIdReferenceFrame = -9000001;
GMAT DefaultSC4.OrbitColor = Red;
GMAT DefaultSC4.TargetColor = Teal;
GMAT DefaultSC4.OrbitErrorCovariance = [ 1e+70 0 0 0 0 0 ; 0 1e+70 0 0 0 0 ; 0 0 1e+70 0 0 0 ; 0 0 0 1e+70 0 0 ; 0 0 0 0 1e+70 0 ; 0 0 0 0 0 1e+70 ];
GMAT DefaultSC4.CdSigma = 1e+70;
GMAT DefaultSC4.CrSigma = 1e+70;
GMAT DefaultSC4.Id = 'SatId';
GMAT DefaultSC4.Attitude = CoordinateSystemFixed;
GMAT DefaultSC4.SPADSRPInterpolationMethod = Bilinear;
GMAT DefaultSC4.SPADSRPScaleFactorSigma = 1e+70;
GMAT DefaultSC4.SPADDragInterpolationMethod = Bilinear;
GMAT DefaultSC4.SPADDragScaleFactorSigma = 1e+70;
GMAT DefaultSC4.AtmosDensityScaleFactorSigma = 1e+70;
GMAT DefaultSC4.ModelFile = 'aura.3ds';
GMAT DefaultSC4.ModelOffsetX = 0;
GMAT DefaultSC4.ModelOffsetY = 0;
GMAT DefaultSC4.ModelOffsetZ = 0;
GMAT DefaultSC4.ModelRotationX = 0;
GMAT DefaultSC4.ModelRotationY = 0;
GMAT DefaultSC4.ModelRotationZ = 0;
GMAT DefaultSC4.ModelScale = 1;
GMAT DefaultSC4.AttitudeDisplayStateType = 'Quaternion';
GMAT DefaultSC4.AttitudeRateDisplayStateType = 'AngularVelocity';
GMAT DefaultSC4.AttitudeCoordinateSystem = EarthMJ2000Eq;
GMAT DefaultSC4.EulerAngleSequence = '321';



%----------------------------------------
%---------- ForceModels
%----------------------------------------

Create ForceModel DefaultProp_ForceModel;
GMAT DefaultProp_ForceModel.CentralBody = Earth;
GMAT DefaultProp_ForceModel.PrimaryBodies = {Earth};
GMAT DefaultProp_ForceModel.PointMasses = {Luna, Sun};
GMAT DefaultProp_ForceModel.SRP = On;
GMAT DefaultProp_ForceModel.RelativisticCorrection = Off;
GMAT DefaultProp_ForceModel.ErrorControl = RSSStep;
GMAT DefaultProp_ForceModel.GravityField.Earth.Degree = 4;
GMAT DefaultProp_ForceModel.GravityField.Earth.Order = 0;
GMAT DefaultProp_ForceModel.GravityField.Earth.StmLimit = 100;
GMAT DefaultProp_ForceModel.GravityField.Earth.PotentialFile = 'JGM2.cof';
GMAT DefaultProp_ForceModel.GravityField.Earth.TideModel = 'None';
GMAT DefaultProp_ForceModel.SRP.Flux = 1367;
GMAT DefaultProp_ForceModel.SRP.SRPModel = Spherical;
GMAT DefaultProp_ForceModel.SRP.Nominal_Sun = 149597870.691;
GMAT DefaultProp_ForceModel.Drag.AtmosphereModel = JacchiaRoberts;
GMAT DefaultProp_ForceModel.Drag.HistoricWeatherSource = 'ConstantFluxAndGeoMag';
GMAT DefaultProp_ForceModel.Drag.PredictedWeatherSource = 'ConstantFluxAndGeoMag';
GMAT DefaultProp_ForceModel.Drag.CSSISpaceWeatherFile = 'SpaceWeather-All-v1.2.txt';
GMAT DefaultProp_ForceModel.Drag.SchattenFile = 'SchattenPredict.txt';
GMAT DefaultProp_ForceModel.Drag.F107 = 190;
GMAT DefaultProp_ForceModel.Drag.F107A = 190;
GMAT DefaultProp_ForceModel.Drag.MagneticIndex = 3;
GMAT DefaultProp_ForceModel.Drag.SchattenErrorModel = 'Nominal';
GMAT DefaultProp_ForceModel.Drag.SchattenTimingModel = 'NominalCycle';
GMAT DefaultProp_ForceModel.Drag.DragModel = 'Spherical';

%----------------------------------------
%---------- Propagators
%----------------------------------------

Create Propagator DefaultProp;
GMAT DefaultProp.FM = DefaultProp_ForceModel;
GMAT DefaultProp.Type = RungeKutta89;
GMAT DefaultProp.InitialStepSize = 60;
GMAT DefaultProp.Accuracy = 9.999999999999999e-12;
GMAT DefaultProp.MinStep = 0.001;
GMAT DefaultProp.MaxStep = 1;
GMAT DefaultProp.MaxStepAttempts = 50;
GMAT DefaultProp.StopIfAccuracyIsViolated = true;

%----------------------------------------
%---------- Subscribers
%----------------------------------------

Create OrbitView DefaultOrbitView;
GMAT DefaultOrbitView.SolverIterations = Current;
GMAT DefaultOrbitView.UpperLeft = [ 0.001282051282051282 0 ];
GMAT DefaultOrbitView.Size = [ 0.5 0.449748743718593 ];
GMAT DefaultOrbitView.RelativeZOrder = 17;
GMAT DefaultOrbitView.Maximized = false;
GMAT DefaultOrbitView.Add = {DefaultSC, DefaultSC2, DefaultSC3, DefaultSC4, Earth};
GMAT DefaultOrbitView.CoordinateSystem = EarthMJ2000Eq;
GMAT DefaultOrbitView.DrawObject = [ true true true true true ];
GMAT DefaultOrbitView.DataCollectFrequency = 1;
GMAT DefaultOrbitView.UpdatePlotFrequency = 50;
GMAT DefaultOrbitView.NumPointsToRedraw = 0;
GMAT DefaultOrbitView.ShowPlot = true;
GMAT DefaultOrbitView.MaxPlotPoints = 20000;
GMAT DefaultOrbitView.ShowLabels = true;
GMAT DefaultOrbitView.ViewPointReference = Earth;
GMAT DefaultOrbitView.ViewPointVector = [ 30000 0 0 ];
GMAT DefaultOrbitView.ViewDirection = Earth;
GMAT DefaultOrbitView.ViewScaleFactor = 1;
GMAT DefaultOrbitView.ViewUpCoordinateSystem = EarthMJ2000Eq;
GMAT DefaultOrbitView.ViewUpAxis = Z;
GMAT DefaultOrbitView.EclipticPlane = Off;
GMAT DefaultOrbitView.XYPlane = On;
GMAT DefaultOrbitView.WireFrame = Off;
GMAT DefaultOrbitView.Axes = On;
GMAT DefaultOrbitView.Grid = Off;
GMAT DefaultOrbitView.SunLine = Off;
GMAT DefaultOrbitView.UseInitialView = On;
GMAT DefaultOrbitView.StarCount = 7000;
GMAT DefaultOrbitView.EnableStars = On;
GMAT DefaultOrbitView.EnableConstellations = On;

Create XYPlot XYPlot2;
GMAT XYPlot2.SolverIterations = Current;
GMAT XYPlot2.UpperLeft = [ 0.3333333333333333 0.3651591289782244 ];
GMAT XYPlot2.Size = [ 0.5 0.449748743718593 ];
GMAT XYPlot2.RelativeZOrder = 5;
GMAT XYPlot2.Maximized = false;
GMAT XYPlot2.XVariable = DefaultSC.ElapsedSecs;
GMAT XYPlot2.YVariables = {DefaultSC.Earth.TA, DefaultSC2.Earth.TA, DefaultSC3.Earth.TA, DefaultSC4.Earth.TA};
GMAT XYPlot2.ShowGrid = true;
GMAT XYPlot2.ShowPlot = true;

Create XYPlot XYPlot1;
GMAT XYPlot1.SolverIterations = Current;
GMAT XYPlot1.UpperLeft = [ 0 0 ];
GMAT XYPlot1.Size = [ 0 0 ];
GMAT XYPlot1.RelativeZOrder = 0;
GMAT XYPlot1.Maximized = false;
GMAT XYPlot1.XVariable = DefaultSC.ElapsedSecs;
GMAT XYPlot1.YVariables = {DefaultSC.EarthMJ2000Eq.RAAN, DefaultSC2.EarthMJ2000Eq.RAAN, DefaultSC3.EarthMJ2000Eq.RAAN, DefaultSC4.EarthMJ2000Eq.RAAN};
GMAT XYPlot1.ShowGrid = true;
GMAT XYPlot1.ShowPlot = true;


%----------------------------------------
%---------- Mission Sequence
%----------------------------------------

BeginMissionSequence;
Propagate DefaultProp(DefaultSC, DefaultSC2, DefaultSC3, DefaultSC4) {DefaultSC.ElapsedSecs = 1};
While DefaultSC.ElapsedSecs < 5400
   Propagate DefaultProp(DefaultSC, DefaultSC2, DefaultSC3, DefaultSC4);
EndWhile;
